### ISSUE TITLE
Detailed Magallanes documentation

### ISSUE THREAD

**Issue by eps90** [andres-montanez/Magallanes#213]
Hi devz! :)
After seeing that many developers encoured problems with Magallanes' tasks configuration I think it's the time to create some developer-friendly documentation. I prepared the list of things that **must be** documented with details. I started to write it some time ago but recently I have completely no time to code after work (I hope it'll change soon!) so I think that every developer can write something and be a living part of this project! :) 

**Here are some basic rules**:
- Documentation is made in markdown
- Developer who wants to describe some part writes a comment here and I (or any collaborator) assign him to this task. This will prevent task duplication.
- Ideally, developer refers **this issue** in his pull requests' description to let us know the progress and make other able to review the document. Then I (or any collaborator) put the issue number next to documentation part in listing below.
- When pull request is merged, I (or any collaborator) ~~strike~~ the issue to mark it as completed.
- If you want to suggest more points to documentation, feel free to write a comment with that (remember that Magallanes has also own website, and there's also something about writing custom tasks, so I didn't mention about on in the list)

So here's the plan of documentaion:
## Deployments
- [ ] **Deployment strategies**
  - [ ] Git-rebase
  - [ ] Git remote cache
  - [ ] RSync
  - [ ] TarGZ
- [ ] **Working with releases**
  - [ ] Releases list
  - [ ] Rollback a release
## Tasks
- [ ] **Composer**
  - [ ] Generate autoload
  - [ ] Install
- [ ] **Filesystem**
  - [ ] Apply FACL
  - [ ] Link shared files
  - [ ] Permissions readable only by web server
  - [ ] Permissions
  - [ ] Permissions writable only by web server
- [ ] **Ioncube**
  - [ ] Encrypt
- [ ] **Magento**
  - [ ] Clear cache
  - [ ] Clear full page cache
- [ ] **SCM**
  - [ ] Chnge branch
  - [ ] Clone
  - [ ] Force update
  - [ ] Remove clone
  - [ ] Update
- [ ] **Symfony2**
  - [ ] Assetic dump
  - [ ] Assets install
  - [ ] Cache clear
  - [ ] Cache warm up
  - [ ] Doctrine migrations
  - [ ] Clean front controller
- [ ] **Manual tasks**
## Commands
- [ ] Add
- [ ] Compile
- [ ] Deploy
- [ ] Init
- [ ] Install
- [ ] List
- [ ] Lock
- [ ] Releases
- [ ] Rollback
- [ ] Unlock
- [ ] Update
- [ ] Upgrade
- [ ] Version
## Working with console
- [ ] Output and logs
  - [ ] Verbose logging
- [ ] Colours

**Comment by drAlberT** [comment]
@eps90 I think you missed the "install" command in the list

**Comment by eps90** [comment]
Yep, you're right ;) Adding!

**Comment by drAlberT** [comment]
:+1:

**Comment by Trudko** [comment]
Hi guys, so far there weren't any contributions were there? I am asking to see some example how it should look like in case I will have time to contribute.

**Comment by eps90** [comment]
@Trudko Unfortunately nobody has contributed here... Quite sad, but even I have no time to write anything here. But I'm very happy that someone wants to improve some things here ! :) I can take some point and describe it to give you an example how to write this. Which points would you like to document first?

**Comment by Trudko** [comment]
Not completely sure yet, I guess we should start with things which are already on the website and which are still correct maybe?

**Comment by andres-montanez** [comment]
Hi all, Version 1 of Magallanes has long reached it's end of life cycle, and so it's documentation. The next mayor version will be well documented from the start.
Many thanks to all!
